--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Johnmacrocraft/Newspaper
branches:
- master
projects:
  Newspaper:
    path: ""
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0.0.0
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
...
